import {useState,useEffect} from 'react';
import {NavLink,Link,useLocation} from 'react-router-dom';
import {Activity,LayoutDashboard,ChartNoAxesCombined,Layers,Newspaper,Sparkles,Wallet,FlaskConical,BookOpen,BrainCircuit,ShieldCheck,NotebookPen,Plug,Settings,ChevronRight,PanelLeftClose,Menu,Power,ArrowUpRight,LogOut,Search,Command,Globe,Shield} from 'lucide-react';
import {Button} from './ui/button';
import {Badge} from './TerminalUI';
import {toast} from './ui/sonner';
import {api,errorText} from '../lib/api';

const groups=[{label:'WORKSPACE',items:[['/','Overview',LayoutDashboard],['/markets','Markets',ChartNoAxesCombined],['/signals','AI Signals',Sparkles],['/paper','Paper Trading',Wallet],['/risk','Risk Center',ShieldCheck]]},{label:'RESEARCH LABS',collapsible:true,items:[['/ledger','Prediction Ledger',BookOpen],['/journal','Trade Journal',NotebookPen],['/models','Model Lab',BrainCircuit],['/backtest','Backtest Lab',FlaskConical],['/options','Options',Layers],['/news','News & Events',Newspaper]]},{label:'SYSTEM',items:[['/health','System Health',Activity],['/connections','API Connections',Plug],['/eligibility','Live Eligibility',Shield],['/settings','Settings',Settings]]}];
export const Logo=()=> <Link to="/" className="brand" data-testid="brand-home"><div className="brand-mark"><ChartNoAxesCombined size={23} strokeWidth={2.7}/></div><div><strong>EDGE<span>INDIA</span></strong><small>INTELLIGENCE TERMINAL</small></div></Link>;
export const Layout=({children,user,onAuth,onLogout,overview,onRefresh})=>{
 const [mobile,setMobile]=useState(false),[clock,setClock]=useState(new Date()),[search,setSearch]=useState(false),[term,setTerm]=useState('');const location=useLocation();
 const [labsOpen,setLabsOpen]=useState(false);
 useEffect(()=>{if(groups[1].items.some(item=>item[0]===location.pathname))setLabsOpen(true);},[location.pathname]);
 useEffect(()=>{setMobile(false);setSearch(false);},[location.pathname]);useEffect(()=>{const id=setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(id);},[]);
 const kill=async()=>{if(!user)return onAuth();try{await api.post('/paper/kill-switch',{enabled:!overview?.account?.kill_switch});onRefresh();toast.success(overview?.account?.kill_switch?'Kill switch released. Other risk controls remain active.':'Kill switch engaged. New paper orders blocked.');}catch(e){toast.error(errorText(e));}};
 return <div className="app-shell">{mobile&&<button data-testid="sidebar-overlay" aria-label="Close menu" className="sidebar-overlay" onClick={()=>setMobile(false)}/>}
 <aside className={`sidebar ${mobile?'open':''}`}><Logo/><div className="workspace-label" data-testid="workspace-label"><div className="workspace-icon">IN</div><div><b>India workspace</b><span>NSE / BSE · Research</span></div><ChevronRight size={14}/></div>
 <nav>{groups.map(group=><div className="nav-group" key={group.label}>{group.collapsible?<button data-testid="research-labs-toggle" className="nav-label nav-group-toggle" aria-expanded={labsOpen} onClick={()=>setLabsOpen(!labsOpen)}>{group.label}<ChevronRight size={15} style={{transform:labsOpen?'rotate(90deg)':'none'}}/></button>:<div className="nav-label">{group.label}</div>}{(!group.collapsible||labsOpen)&&group.items.map(([path,label,Icon])=><NavLink end={path==='/'} data-testid={`nav-${path==='/'?'overview':path.slice(1)}`} key={path} to={path} className={({isActive})=>`nav-item ${isActive?'active':''}`}><Icon size={17}/><span>{label}</span>{label==='AI Signals'&&<span className="nav-count">{overview?.predictions_count||0}</span>}{label==='API Connections'&&<span className="nav-dot"/>}</NavLink>)}</div>)}</nav>
 <div className="sidebar-bottom"><div className="paper-safe" data-testid="paper-safety-notice"><ShieldCheck size={17}/><div><b>Capital protected.</b><span>Real execution disabled</span></div></div><button className="profile-button" data-testid="workspace-profile" onClick={user?onLogout:onAuth}><span className="avatar">{user?user.name.slice(0,2).toUpperCase():'RE'}</span><span><b>{user?.name||'Research workspace'}</b><small>{user?'Personal account':'Not signed in'}</small></span>{user?<LogOut size={15}/>:<ArrowUpRight size={15}/>}</button></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button data-testid="mobile-menu-button" className="icon-button mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(!mobile)}><Menu size={21}/></button><PanelLeftClose size={16} className="desktop-icon"/><span>Workspace</span><ChevronRight size={13}/><b>{groups.flatMap(g=>g.items).find(i=>i[0]===location.pathname)?.[1]||'Research'}</b></div><div className="topbar-actions"><button className="search-button" data-testid="global-search-button" onClick={()=>setSearch(!search)} aria-label="Search pages"><Search size={15}/><span>Search terminal</span><kbd>⌕</kbd></button><span className="topbar-divider"/><Badge tone="cyan" id="paper-mode-badge">PAPER MODE</Badge><button data-testid="kill-switch-button" className={`kill-button ${overview?.account?.kill_switch?'engaged':''}`} onClick={kill}><Power size={14}/><span>Kill switch</span></button>{!user&&<Button variant="outline" size="sm" data-testid="sign-in-button" onClick={onAuth}>Sign in <ArrowUpRight size={13}/></Button>}</div></header>
 {search&&<div className="search-dropdown"><input autoFocus data-testid="global-search-input" placeholder="Find a page…" value={term} onChange={e=>setTerm(e.target.value)}/>{groups.flatMap(g=>g.items).filter(i=>i[1].toLowerCase().includes(term.toLowerCase())).map(([p,l])=><Link data-testid={`search-result-${p==='/'?'overview':p.slice(1)}`} key={p} to={p}>{l}<ArrowUpRight size={14}/></Link>)}</div>}
 <div className="market-strip"><div className="market-context"><Globe size={14}/><b>INDIA</b><span className="market-separator"/> <span>{overview?.connections?.find(c=>c.provider===(overview?.market_provider||'upstox'))?.status==='CONNECTED'?'REST feed':'Feed offline'}</span></div>{[['NIFTY 50','NSE:NIFTY50-INDEX'],['BANK NIFTY','NSE:NIFTYBANK-INDEX'],['INDIA VIX','NSE:INDIAVIX-INDEX']].map(([t,s])=>{const q=overview?.quotes?.find(q=>q.symbol===s);return <div className="ticker-strip-item" key={t} data-testid={`strip-${t.replaceAll(' ','-').toLowerCase()}`}><span>{t}</span><b>{q?.ltp?.toLocaleString('en-IN')||'—'}</b><small>{q?q.freshness:'Awaiting data'}</small></div>})}<div className="ist-clock" data-testid="ist-clock">{clock.toLocaleTimeString('en-GB',{timeZone:'Asia/Kolkata'})}<span>IST</span></div></div>
 <main>{children}</main><footer className="terminal-footer"><span data-testid="footer-system-status"><i className="status-dot amber"/> {overview?.system_status||'AWAITING CONNECTIONS'}</span><span>Research, not financial advice.</span><span data-testid="footer-version">TradingAgents v0.6.0 <span className="muted">/</span> <Shield size={11}/> PAPER ONLY</span></footer></div></div>
};