import {useState,useEffect,useRef} from 'react';
import {Link} from 'react-router-dom';
import {ChartCandlestick,Maximize2,SlidersHorizontal,Radio,ArrowUpRight} from 'lucide-react';
import {api,errorText,money} from '../lib/api';
import {Badge,ConnectButton} from './TerminalUI';
import {Button} from './ui/button';

export const MarketChart=({user,symbol='NSE:NIFTY50-INDEX',name='NIFTY 50',connected=false,large=false,provider='Upstox'})=>{
 useEffect(()=>{const timer=setInterval(()=>setQuote(q=>q?.freshness==='FRESH'&&Date.now()-new Date(q.source_timestamp).getTime()>15000?{...q,freshness:'STALE'}:q),1000);return()=>clearInterval(timer);},[]);
 const [tf,setTf]=useState('5'),[candles,setCandles]=useState([]),[quote,setQuote]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[expanded,setExpanded]=useState(false);const host=useRef(null);
 useEffect(()=>{let active=true,inFlight=false;setCandles([]);setQuote(null);setError('');if(!user||!connected)return;const load=async()=>{if(inFlight)return;inFlight=true;setBusy(true);try{const results=await Promise.allSettled([api.get('/markets/candles',{params:{symbol,resolution:tf}}),api.get('/markets/quote',{params:{symbol}})]);if(!active)return;if(results[0].status==='fulfilled'){setCandles(results[0].value.data.candles);setError('');}else setError(errorText(results[0].reason));if(results[1].status==='fulfilled')setQuote(results[1].value.data.quote);}finally{inFlight=false;if(active)setBusy(false);}};load();const id=setInterval(load,15000);return()=>{active=false;clearInterval(id);};},[tf,symbol,user,connected,provider]);
 useEffect(()=>{if(!host.current||!candles.length)return;let chart;let disposed=false;import('lightweight-charts').then(({createChart,CandlestickSeries})=>{if(disposed)return;chart=createChart(host.current,{autoSize:true,layout:{background:{color:'#171c22'},textColor:'#c1d0df',fontFamily:'JetBrains Mono',fontSize:12},grid:{vertLines:{color:'#35414a'},horzLines:{color:'#35414a'}},rightPriceScale:{borderColor:'#617589'},timeScale:{borderColor:'#617589',timeVisible:true}});const series=chart.addSeries(CandlestickSeries,{upColor:'#75d2af',downColor:'#f29ca7',borderVisible:false,wickUpColor:'#75d2af',wickDownColor:'#f29ca7'});series.setData(candles.map(c=>({time:c.time,open:c.open,high:c.high,low:c.low,close:c.close})));chart.timeScale().fitContent();});return()=>{disposed=true;chart?.remove();};},[candles,expanded]);
 return <section className={`chart-panel ${large?'large-chart':''} ${expanded?'chart-expanded':''}`} data-testid="market-chart-panel"><div className="chart-top"><div className="chart-instrument"><span className="instrument-icon"><ChartCandlestick size={19}/></span><div><h2 data-testid="chart-instrument-name">{name}<span>NSE</span></h2><div className="chart-price" data-testid="chart-price">{money(quote?.ltp)}<span>{quote?.change_pct!=null?`${quote.change_pct}%`:'No live data'}</span></div></div></div><Badge tone={quote?.freshness==='FRESH'?'green':'amber'} id="chart-feed-status">{quote?.freshness==='FRESH'?'LIVE · REST':quote?'DATA '+quote.freshness:'FEED DISCONNECTED'}</Badge></div>
 <div className="chart-toolbar"><div className="timeframes">{[['1','1m'],['5','5m'],['15','15m'],['30','30m'],['60','1h'],['D','1D']].map(([value,label])=><button data-testid={`chart-timeframe-${value}`} key={value} onClick={()=>setTf(value)} className={tf===value?'selected':''}>{label}</button>)}</div><div className="chart-tools"><span className="candle-label"><ChartCandlestick size={14}/> Candles</span><button data-testid="chart-expand" className="icon-button" title={expanded?'Minimize chart':'Expand chart'} aria-label="Expand chart" onClick={()=>setExpanded(!expanded)}><Maximize2 size={14}/></button></div></div>
 <div className="chart-canvas" data-testid="chart-canvas" ref={host}>{!candles.length&&<div className="chart-empty"><div className="chart-connection-icon"><Radio size={25} strokeWidth={1.3}/><span/></div><h3 data-testid="chart-empty-title">{busy?'Fetching market data…':'Every edge starts with real data.'}</h3><p data-testid="chart-empty-description">{error||`Connect ${provider} to view verified market prices.`}</p><ConnectButton id="chart-connect-provider" provider={provider}/><span className="chart-empty-footnote">No simulated prices. No assumptions.</span></div>}</div>
 <div className="chart-footer" data-testid="chart-footer"><span><i className={`status-dot ${quote?.freshness==='FRESH'?'green':'muted-dot'}`}/> {quote?`${quote.provider} · REST refresh 15s`:`Awaiting ${provider} connection`}</span><span>Source: {quote?.source_timestamp?new Date(quote.source_timestamp).toLocaleTimeString('en-GB',{timeZone:'Asia/Kolkata'}):'—'} <span className="chart-timezone">UTC+5:30</span></span></div></section>
};