import {useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {Wallet,TrendingUp,ShieldCheck,RefreshCw,ArrowUpRight,Plus,Receipt,BookOpen} from 'lucide-react';
import {PageHeading,Badge,Metric,EmptyState} from '../components/TerminalUI';
import {Button} from '../components/ui/button';
import {toast} from '../components/ui/sonner';
import {api,errorText,money,formatTime} from '../lib/api';

export default function PaperTrading({user,onAuth,overview,onRefresh}){
 const [tab,setTab]=useState('positions'),[items,setItems]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({symbol:'NSE:RELIANCE-EQ',quantity:1,stop:'',target:''});const a=overview?.account;
 useEffect(()=>{api.get('/markets/instruments').then(r=>setItems(r.data.instruments.filter(x=>x.type==='EQUITY'))).catch(()=>{});},[]);
 const submit=async e=>{e.preventDefault();if(!user)return onAuth();setBusy(true);setError('');try{await api.post('/paper/orders',{...form,quantity:Number(form.quantity),stop:Number(form.stop),target:Number(form.target),idempotency_key:crypto.randomUUID()});toast.success('Paper order filled.');onRefresh();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const refresh=async()=>{if(!user)return onAuth();setBusy(true);try{await api.post('/paper/refresh');onRefresh();toast.success('Paper account refreshed.');}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
 const close=async id=>{setBusy(true);try{await api.post(`/paper/positions/${id}/close`);onRefresh();toast.success('Paper position closed.');}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
 const rows=tab==='positions'?a?.positions||[]:a?.orders?.slice().reverse()||[];
 return <><PageHeading eyebrow="EXECUTION / SIMULATED CAPITAL" title="Paper trading" subtitle="Real market data. Simulated orders. Every trade accountable."><Button data-testid="refresh-paper-account" variant="outline" onClick={refresh} disabled={busy}><RefreshCw size={14}/> Refresh positions</Button><Badge tone="cyan" id="paper-execution-badge">NO REAL ORDERS</Badge></PageHeading>
 <div className="metrics-row"><Metric label="Cash balance" value={a?money(a.cash):'—'} note="Available paper capital" icon={Wallet} id="paper-cash"/><Metric label="Realized P&L" value={a?money(a.realized_pnl):'—'} note={`${a?.trades.length||0} closed trades`} icon={TrendingUp} id="paper-realized-pnl"/><Metric label="Unrealized P&L" value={money(a?.unrealized_pnl)} note="Fresh marks required" icon={TrendingUp} id="paper-unrealized-pnl"/><Metric label="Fees paid" value={a?money(a.fees_paid):'—'} note="Estimated equity-intraday fees" icon={Receipt} id="paper-fees"/></div>
 {!user&&<div className="prerequisite-note" data-testid="paper-auth-notice">Create an account to initialize ₹10,00,000 in paper capital.<Button data-testid="paper-sign-in" onClick={onAuth} variant="outline">Open workspace <ArrowUpRight size={13}/></Button></div>}
 <div className="paper-order-layout"><div className="paper-tab-content"><div className="tabs-row">{['positions','orders'].map(t=><button key={t} data-testid={`paper-tab-${t}`} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='positions'?'Open positions':'Order history'} <span className="muted">{t==='positions'?a?.positions.length||0:a?.orders.length||0}</span></button>)}</div><div className="table-wrap"><table className="data-table" data-testid="paper-table"><thead><tr>{(tab==='positions'?['INSTRUMENT','QTY','ENTRY','P&L','ACTION']:['INSTRUMENT','SIDE','FILL','STATUS','TIME']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{!rows.length?<tr className="table-empty"><td colSpan={5}><EmptyState id="paper-empty-state" icon={Wallet} title={tab==='positions'?'No open positions. No unnecessary risk.':'Your order history starts with discipline.'} text={tab==='positions'?'A fresh quote and every risk check must pass before a paper position can open.':'Every fill is recorded with slippage, fees and its source quote timestamp.'}/></td></tr>:rows.map(row=><tr key={row.id} data-testid={`paper-row-${row.id}`}><td>{row.symbol.replace('NSE:','').replace('-EQ','')}</td>{tab==='positions'?<><td className="mono">{row.quantity}</td><td className="mono">{money(row.entry)}</td><td className="mono">{money(row.unrealized_pnl)}</td><td><button data-testid={`close-position-${row.id}`} className="text-link" onClick={()=>close(row.id)} disabled={busy}>Close</button></td></>:<><td>{row.side}</td><td className="mono">{money(row.fill)}</td><td><Badge tone="green">{row.status}</Badge></td><td>{formatTime(row.timestamp)}</td></>}</tr>)}</tbody></table></div><div className="security-note" data-testid="paper-monitoring-disclosure"><ShieldCheck size={17}/><span>Stops and targets are checked on “Refresh positions”, not continuously. Unattended stop monitoring is not enabled. Gap exits use the current bid, not a guaranteed stop price.</span></div></div>
 <form className="order-ticket" onSubmit={submit}><h2>New paper order</h2><div className="form-stack"><label>Instrument<select data-testid="paper-order-symbol" value={form.symbol} onChange={e=>setForm({...form,symbol:e.target.value})}>{items.map(i=><option key={i.symbol} value={i.symbol}>{i.name}</option>)}</select></label><label>Quantity<input data-testid="paper-order-quantity" type="number" min="1" step="1" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Stop-loss price (₹)<input data-testid="paper-order-stop" type="number" min="0.01" step="0.01" required placeholder="0.00" value={form.stop} onChange={e=>setForm({...form,stop:e.target.value})}/></label><label>Target price (₹)<input data-testid="paper-order-target" type="number" min="0.01" step="0.01" required placeholder="0.00" value={form.target} onChange={e=>setForm({...form,target:e.target.value})}/></label>{error&&<div role="alert" data-testid="paper-order-error" className="form-error">{error}</div>}<Button data-testid="paper-place-order" className="primary-button" disabled={busy}><ShieldCheck size={14}/>{busy?'Checking…':'Check risk & buy paper'}</Button></div><p className="fee-note" data-testid="paper-fee-assumptions">LONG EQUITIES ONLY<br/>Fill: live ask + 5 bps slippage. Brokerage: 0.03%, capped at ₹20/order, plus estimated exchange, SEBI, GST, stamp duty and STT. Not a broker invoice.</p></form></div></>;
}