import {useState,useEffect,useCallback} from 'react';
import {Link} from 'react-router-dom';
import {Sparkles,Activity,Network,ShieldCheck,BrainCircuit,Play,LoaderCircle,ArrowUpRight,RefreshCw,BookOpen,Download,LockKeyhole} from 'lucide-react';
import {PageHeading,Badge,EmptyState,Metric} from '../components/TerminalUI';
import {Button} from '../components/ui/button';
import {toast} from '../components/ui/sonner';
import {api,errorText,formatTime,money} from '../lib/api';

export const Signals=({user,onAuth,onRefresh})=>{
 const [symbol,setSymbol]=useState('NSE:NIFTY50-INDEX'),[items,setItems]=useState([]),[runs,setRuns]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[report,setReport]=useState(null);
 const load=useCallback(()=>{if(user)api.get('/research/runs').then(r=>setRuns(r.data.runs)).catch(e=>toast.error(errorText(e)));else {setRuns([]);setReport(null);}},[user]);
 useEffect(()=>{api.get('/markets/instruments').then(r=>setItems(r.data.instruments)).catch(()=>{});load();},[load]);
 const run=async()=>{if(!user)return onAuth();setBusy(true);setError('');try{const {data}=await api.post('/research/run',{symbol},{timeout:270000});setReport(data.run);load();onRefresh();toast.success(data.cached?'Existing research loaded for this snapshot.':'Research complete. No order was placed.');}catch(e){setError(errorText(e));load();}finally{setBusy(false);}};
 return <>
  <PageHeading eyebrow="INTELLIGENCE / UPSTREAM LANGGRAPH" title="AI signals" subtitle="Evidence first. Debate second. Risk always."><Badge id="signals-posture" tone="amber">NO TRADE</Badge></PageHeading>
  <div className="filter-bar"><select data-testid="research-symbol" aria-label="Research instrument" value={symbol} onChange={e=>setSymbol(e.target.value)}>{items.map(i=><option value={i.symbol} key={i.symbol}>{i.name}</option>)}</select><Button data-testid="run-research-button" className="primary-button" onClick={run} disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:<Play size={16}/>} {busy?'Agents are researching…':'Run research'}</Button></div>
  {error&&<div data-testid="research-error" className="form-error" role="alert">{error}</div>}
  <div className="agent-flow">{[[Activity,'Technical analyst','Verified broker candles and local indicators.','01 / ANALYZE'],[Network,'Bull & bear debate','Both sides of the thesis, reviewed by a research manager.','02 / CHALLENGE'],[BrainCircuit,'Trader & portfolio','A reasoned proposal, not an executable order.','03 / SYNTHESIZE'],[ShieldCheck,'Risk gate','Independent limits, data checks, and a right to say no.','04 / PROTECT']].map(([Icon,title,description,label])=><div className="agent-stage" key={title} data-testid={`agent-stage-${label.slice(0,2)}`}><Icon size={25}/><h3>{title}</h3><p>{description}</p><span>{label}</span></div>)}</div>
  <div className="security-note" data-testid="research-scope"><ShieldCheck size={19}/>Technical-only research in this release. News, macro, sentiment and options agents await validated sources. Ratings are not calibrated probabilities of profit.</div>
  <section className="content-section"><h2 className="section-title">Research history</h2>
   {!runs.length?<EmptyState id="research-empty-state" icon={Sparkles} title="Nothing to rush. Everything to verify." text="Connect your selected market-data provider and Gemini, then analyze a fresh snapshot. Every completed run is traceable to its input data." action={<Button asChild variant="outline" data-testid="research-connect-button"><Link to="/connections">API connections <ArrowUpRight size={15}/></Link></Button>}/>:<div className="table-wrap"><table className="data-table" data-testid="research-runs-table"><thead><tr><th>ASSET</th><th>TIMESTAMP</th><th>STATUS</th><th>REPORT</th></tr></thead><tbody>{runs.map(run=><tr key={run.id} data-testid={`research-run-${run.id}`}><td>{run.symbol}</td><td>{formatTime(run.timestamp)}</td><td><Badge tone={run.status==='COMPLETED'?'green':'amber'}>{run.status}</Badge></td><td><button data-testid={`view-report-${run.id}`} className="text-link" onClick={()=>setReport(run)}>View report <ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div>}
   {report&&<div className="run-report" data-testid="research-report">{report.result?.report||report.result?.error||`Run status: ${report.status}`}</div>}
  </section>
 </>;
};

export const Ledger=({user,onAuth})=>{
 const [items,setItems]=useState([]),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[selected,setSelected]=useState(null);
 const load=useCallback(()=>{if(user)api.get('/ledger').then(r=>setItems(r.data.predictions)).catch(e=>toast.error(errorText(e)));else {setItems([]);setSelected(null);}},[user]);
 useEffect(()=>{load();},[load]);
 const settle=async()=>{if(!user)return onAuth();setBusy(true);try{const {data}=await api.post('/ledger/settle');toast.success(data.message);load();}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
 const exportData=()=>{const blob=new Blob([JSON.stringify(items,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='edge-india-predictions.json';link.click();URL.revokeObjectURL(url);toast.success('Ledger exported.');};
 const rows=items.filter(p=>filter==='all'||(filter==='settled'?!!p.outcome:!p.outcome));
 return <><PageHeading eyebrow="RESEARCH / ACCOUNTABILITY" title="Prediction ledger" subtitle="Every forecast recorded. Every outcome measured. Nothing rewritten."><Button data-testid="settle-predictions" variant="outline" onClick={settle} disabled={busy}><RefreshCw size={14}/>{busy?'Evaluating…':'Evaluate due'}</Button><Button data-testid="export-ledger" variant="outline" disabled={!items.length} onClick={exportData}><Download size={14}/> Export</Button></PageHeading><div className="metrics-row"><Metric label="Total predictions" value={items.length} note="Immutable original records" icon={BookOpen} id="ledger-total"/><Metric label="Awaiting outcome" value={items.filter(p=>!p.outcome).length} note="No missing prices substituted" icon={Activity} id="ledger-pending"/><Metric label="Evaluated" value={items.filter(p=>p.outcome).length} note="Exact-horizon completed bars" icon={ShieldCheck} id="ledger-settled"/><Metric label="Calibration" value="NOT AVAILABLE" note="Insufficient validated evidence" icon={BrainCircuit} id="ledger-calibration"/></div><div className="tabs-row">{['all','pending','settled'].map(f=><button data-testid={`ledger-filter-${f}`} key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f==='all'?'All predictions':f==='pending'?'Pending':'Evaluated'}</button>)}</div><div className="table-wrap"><table className="data-table" data-testid="prediction-ledger-table"><thead><tr><th>ASSET / CREATED</th><th>HORIZON</th><th>DIRECTION</th><th>PROBABILITY</th><th>OUTCOME</th><th>RECORD</th></tr></thead><tbody>{rows.length?rows.map(p=><tr key={p.prediction_id} data-testid={`prediction-${p.prediction_id}`}><td>{p.asset}<br/><small>{formatTime(p.timestamp)}</small></td><td>{p.horizon}</td><td>{p.direction}</td><td>{p.probability==null?'Uncalibrated':`${p.probability*100}%`}</td><td>{p.outcome?`${(p.outcome.actual_return*100).toFixed(3)}%`:'Pending'}</td><td><button data-testid={`prediction-details-${p.prediction_id}`} className="text-link" onClick={()=>setSelected(p)}>Inspect</button></td></tr>):<tr className="table-empty"><td colSpan={6}><EmptyState id="ledger-empty-state" icon={BookOpen} title="An empty ledger is an honest ledger." text="Predictions appear only after a completed research run on validated data. No simulated forecasts, no retrospective edits." action={<Button asChild variant="outline" data-testid="ledger-to-signals"><Link to="/signals">Open AI signals <ArrowUpRight size={13}/></Link></Button>}/></td></tr>}</tbody></table></div>{selected&&<div className="run-report" data-testid="prediction-detail">{JSON.stringify(selected,null,2)}</div>}<div className="security-note" data-testid="ledger-immutability-note"><LockKeyhole size={17}/>Original prediction records are insert-only through this API. Outcomes are stored separately. Probability stays unavailable until a calibrated model supports it.</div></>;
};