import {useEffect,useState} from 'react';
import {ShieldCheck,Save,Power,RotateCcw,LockKeyhole} from 'lucide-react';
import {PageHeading,Badge} from '../components/TerminalUI';
import {Button} from '../components/ui/button';
import {toast} from '../components/ui/sonner';
import {api,errorText,money} from '../lib/api';
const defaults={risk_per_trade:.5,daily_loss_limit:2,max_consecutive_losses:3,max_trades_day:10,cooldown_seconds:60,max_exposure:30,max_position:10,min_risk_reward:2,min_volume:1000,max_spread_bps:25};
const fields=[['risk_per_trade','Maximum risk per trade','% of starting capital',.1,2,.1],['daily_loss_limit','Daily loss limit','% of starting capital',.1,10,.1],['max_consecutive_losses','Loss-streak cooldown','Consecutive losing trades',1,10,1],['max_trades_day','Maximum trades per day','New positions per IST trading day',1,50,1],['cooldown_seconds','Trade cooldown','Seconds between executions',30,3600,1],['max_exposure','Maximum total exposure','% of starting capital',1,100,1],['max_position','Maximum position size','% of starting capital',1,25,1],['min_risk_reward','Minimum risk / reward','Evaluated after slippage',1,10,.1],['min_volume','Minimum daily volume','Shares · missing volume blocks orders',1000,1000000000,1],['max_spread_bps','Maximum bid / ask spread','Basis points',1,100,1]];
export default function RiskCenter({user,onAuth,overview,onRefresh}){
 const [form,setForm]=useState(defaults),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 useEffect(()=>{if(overview?.account?.risk&&!dirty)setForm(overview.account.risk);},[overview,dirty]);
 const save=async e=>{e.preventDefault();if(!user)return onAuth();setBusy(true);try{await api.put('/paper/risk',form);setDirty(false);onRefresh();toast.success('Risk guardrails saved.');}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
 const kill=async()=>{if(!user)return onAuth();try{await api.post('/paper/kill-switch',{enabled:!overview?.account?.kill_switch});onRefresh();toast.success('Kill switch updated.');}catch(e){toast.error(errorText(e));}};
 return <><PageHeading eyebrow="RISK / CAPITAL PROTECTION" title="Risk center" subtitle="Hard limits. Clear boundaries. No exceptions from the AI."><Badge tone="green" id="risk-engine-status">DETERMINISTIC ENGINE</Badge></PageHeading>{!user&&<div className="prerequisite-note" data-testid="risk-sign-in-notice">Default paper settings. Sign in to save your own risk limits.</div>}<div className="risk-layout"><form onSubmit={save}><div className="risk-form">{fields.map(([key,label,hint,min,max,step])=><label className="risk-field" key={key}><span>{label}</span><input data-testid={`risk-${key.replaceAll('_','-')}`} type="number" min={min} max={max} step={step} required value={form[key]} onChange={e=>{setDirty(true);setForm({...form,[key]:e.target.value===''?'':Number(e.target.value)});}}/><small>{hint}</small></label>)}</div><div className="form-actions"><Button data-testid="save-risk-settings" className="primary-button" disabled={busy} type="submit"><Save size={14}/>{busy?'Saving…':'Save guardrails'}</Button><Button data-testid="reset-risk-form" type="button" variant="outline" onClick={()=>{setForm(defaults);setDirty(true);}}><RotateCcw size={14}/> Reset form</Button></div></form><aside className="risk-summary"><h2>Capital at risk</h2><div className="risk-preview-row"><span>Starting capital</span><b>{money(1000000)}</b></div><div className="risk-preview-row"><span>Maximum risk / trade</span><b data-testid="risk-amount-preview">{money(1000000*form.risk_per_trade/100)}</b></div><div className="risk-preview-row"><span>Daily loss threshold</span><b>{money(1000000*form.daily_loss_limit/100)}</b></div><div className="risk-preview-row"><span>Live execution</span><Badge id="risk-live-execution">DISABLED</Badge></div><p>Missing or stale market data blocks every new order. Bid/ask spread, volume, cooldowns, exposure and available cash must all pass independently.</p><div className="danger-zone"><h3>Emergency kill switch</h3><p>Stops new paper orders and research generation. Existing positions remain open; risk-reducing closes still require fresh market data.</p><button className={`kill-button ${overview?.account?.kill_switch?'engaged':''}`} data-testid="risk-kill-switch" onClick={kill}><Power size={15}/>{overview?.account?.kill_switch?'Release kill switch':'Engage kill switch'}</button></div></aside></div><div className="security-note" data-testid="risk-policy-note"><ShieldCheck size={17}/>The AI can propose. Only the deterministic risk engine can approve. No LLM output can place an order.</div></>;
}