import {useState,useEffect,useCallback} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {Activity,Database,Radio,Sparkles,ShieldCheck,Server,RefreshCw,ArrowUpRight,LockKeyhole,FlaskConical,Layers,Newspaper,BrainCircuit,BookOpen,AlertTriangle,CheckCircle2,Network} from 'lucide-react';
import {PageHeading,Badge,EmptyState,Metric} from '../components/TerminalUI';
import {Button} from '../components/ui/button';
import {toast} from '../components/ui/sonner';
import {api,errorText,formatTime,money} from '../lib/api';
import {ThemePreferences} from '../components/ThemeControls';

export const SystemHealth=({user,overview,onAuth})=>{
 const [data,setData]=useState(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);try{const {data}=await api.get(user?'/system':'/health');setData(data);}catch(e){toast.error(errorText(e));}finally{setBusy(false);}},[user]);
 useEffect(()=>{load();},[load]);
 const status=p=>overview?.connections?.find(c=>c.provider===p)?.status||'DISCONNECTED';
 const selected=overview?.market_provider||'upstox';
 const cards=[[Database,'Database',data?.database||'CHECKING','MongoDB persistence and atomic paper-account updates.'],[Radio,'Market feed',status(selected),`${selected==='upstox'?'Upstox':'FYERS'} REST quotes and completed candles. Source-time freshness enforced.`],[Sparkles,'AI engine',status('gemini'),'TradingAgents v0.6.0 with isolated Gemini credentials.'],[ShieldCheck,'Broker execution','DISABLED','No real-order submission path exists in this release.'],[Network,'WebSocket stream','NOT ENABLED','Broker streaming integration is a subsequent phase.'],[Server,'Redis / durable queue','NOT CONFIGURED','Single-instance first delivery. Distributed queue migration documented.']];
 return <><PageHeading eyebrow="SYSTEM / OBSERVABILITY" title="System health" subtitle="Know what’s connected. Know what’s missing. Fail safely."><Button data-testid="refresh-health" variant="outline" onClick={load} disabled={busy}><RefreshCw size={14}/>{busy?'Checking…':'Refresh health'}</Button></PageHeading><div className="health-grid">{cards.map(([Icon,title,value,description],i)=><div className="health-item" key={title} data-testid={`health-component-${i}`}><div className="health-item-head"><Icon size={21}/><Badge tone={value==='CONNECTED'?'green':value==='DISABLED'?'muted':'amber'}>{value}</Badge></div><h3>{title}</h3><p>{description}</p></div>)}</div><p className="health-refreshed" data-testid="health-last-checked">LAST CHECKED · {formatTime(data?.timestamp)}</p><section className="content-section"><h2 className="section-title">System event log</h2>{data?.events?.length?<div className="table-wrap"><table className="data-table" data-testid="system-event-table"><thead><tr><th>TIMESTAMP</th><th>EVENT</th><th>DETAIL</th></tr></thead><tbody>{data.events.map(e=><tr key={e.id}><td>{formatTime(e.timestamp)}</td><td>{e.event.replaceAll('_',' ')}</td><td>{JSON.stringify(e.detail)}</td></tr>)}</tbody></table></div>:<EmptyState id="health-events-empty" icon={Activity} title="No system events to display." text={user?'Events appear as you configure connections and use the workspace.':'Opening your private workspace event log.'}/>}</section></>;
};

export const Settings=({user})=> <>
 <PageHeading eyebrow="WORKSPACE / PREFERENCES" title="Settings" subtitle="Your workspace. Your keys. No account required."/>
 <ThemePreferences/>
 <div className="settings-list">{[['Workspace',user?.is_guest?'Browser workspace':user?.name||'My workspace','Opens automatically. No email or password needed.'],['Workspace access','THIS BROWSER','A private cookie keeps your workspace available for 90 days of activity. Clearing cookies loses access; other browsers start separately.'],['Execution mode','PAPER ONLY','Real broker orders are not supported.'],['Starting capital','₹10,00,000','Each workspace starts with independent simulated capital.'],['Reporting currency','INR (₹)','Indian numbering format.'],['Market timezone','Asia/Kolkata','UTC+05:30 · risk day boundaries use IST.'],['Research foundation','TradingAgents 0.6.0','Apache-2.0 · Tauric Research. Original multi-agent graph with isolated provider keys.'],['Research scope','TECHNICAL ONLY','Market analyst, Bull/Bear debate, Trader, risk debate and Portfolio Manager. Indian news, fundamentals, social and options sources are not connected.'],['Data retention','Append-only ledger','Predictions have no edit or delete endpoint.']].map(([title,value,description],i)=><div className="settings-row" key={title} data-testid={`settings-row-${i}`}><div><h3>{title}</h3><p>{description}</p></div><b>{value}</b></div>)}</div>
 <div className="form-actions"><Button asChild variant="outline" data-testid="settings-risk-link"><Link to="/risk">Edit risk limits <ArrowUpRight size={14}/></Link></Button><Button asChild variant="outline" data-testid="settings-connections-link"><Link to="/connections">Manage connections <ArrowUpRight size={14}/></Link></Button><Button asChild variant="outline" data-testid="upstream-repository-link"><a href="https://github.com/TauricResearch/TradingAgents" target="_blank" rel="noreferrer">Original TradingAgents repository <ArrowUpRight size={14}/></a></Button></div>
 </>;

export const Eligibility=()=> <><PageHeading eyebrow="COMPLIANCE / RELEASE GATES" title="Live eligibility" subtitle="API access is not permission to automate real-money trading."><Badge tone="amber" id="live-go-no-go">NO-GO</Badge></PageHeading><div className="security-note" data-testid="eligibility-disabled"><LockKeyhole size={18}/>Real execution is disabled by design. There is no enable switch or order route in this release.</div><div className="eligibility-list">{[['Broker capability & authentication','Confirm broker-supported automation, permissions, token lifecycle and onboarding.'],['Static IP & algo identification','Verify current broker and exchange requirements for static IPs and algorithm identifiers.'],['Registration & regulatory requirements','Review applicable SEBI, NSE and broker rules with qualified compliance advice. No legal eligibility is assumed.'],['Out-of-sample statistical evidence','Positive cost-adjusted expectancy, controlled drawdown, stable calibration and performance across regimes.'],['Execution & operational resilience','Validated fills, slippage robustness, outage recovery, monitoring, kill switch and daily loss controls.']].map(([title,text],i)=><div className="eligibility-item" key={title} data-testid={`eligibility-check-${i}`}><AlertTriangle size={18}/><div><h3>{title}</h3><p>{text}</p></div><Badge tone="amber">NOT VERIFIED</Badge></div>)}</div></>;

export const Journal=({overview})=>{const rows=overview?.account?.trades||[];return <><PageHeading eyebrow="EXECUTION / REFLECTION" title="Trade journal" subtitle="A complete record of what happened, not what might have happened."/><div className="metrics-row"><Metric label="Closed trades" value={rows.length} note="Cost-adjusted paper outcomes" icon={BookOpen} id="journal-trades"/><Metric label="Net realized P&L" value={overview?.account?money(overview.account.realized_pnl):'—'} note="Includes entry and exit fees" icon={Activity} id="journal-pnl"/><Metric label="Win rate" value={rows.length?`${(rows.filter(t=>t.pnl>0).length/rows.length*100).toFixed(1)}%`:'—'} note="No trades, no claimed performance" icon={ShieldCheck} id="journal-winrate"/><Metric label="Strategy evidence" value="INSUFFICIENT" note="Out-of-sample testing required" icon={FlaskConical} id="journal-evidence"/></div>{!rows.length?<EmptyState id="journal-empty" icon={BookOpen} title="The best journal starts with a plan." text="Closed paper trades will appear here with entry, exit, costs, P&L and the reason for closing." action={<Button asChild variant="outline" data-testid="journal-to-paper"><Link to="/paper">Paper trading <ArrowUpRight size={13}/></Link></Button>}/>:<div className="table-wrap"><table className="data-table" data-testid="journal-table"><thead><tr><th>ASSET</th><th>ENTRY</th><th>EXIT</th><th>NET P&L</th><th>REASON</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td>{t.symbol}</td><td>{money(t.entry)}</td><td>{money(t.exit)}</td><td>{money(t.pnl)}</td><td>{t.reason}</td></tr>)}</tbody></table></div>}</>};

const modules={options:{title:'Options intelligence',icon:Layers,description:'Liquidity before leverage. Evidence before a candidate.',empty:'No option chain connected.',text:'A licensed chain, expiry and lot metadata, valid bid/ask quotes and open interest are required. Greeks are never invented.',requirements:['Licensed NSE F&O data','Validated chain and expiry metadata','Liquidity and spread checks']},news:{title:'News & events',icon:Newspaper,description:'Public information. Traceable sources. Measurable impact.',empty:'No verified news feed connected.',text:'News ingestion is a later phase. No headlines, sentiment or impact scores are generated without a traceable public source.',requirements:['Public or licensed news feed','Exchange and company announcements','Source-time event normalization']},backtest:{title:'Backtest lab',icon:FlaskConical,description:'Every strategy must face data it has never seen.',empty:'Good results start with honest data.',text:'Point-in-time data and a validated execution model are required before an India intraday backtest can run. Upstream decision scoring is not a portfolio backtest.',requirements:['Point-in-time market archive','Cost-adjusted execution model','Train / validation / out-of-sample split']}};
export const PlannedModule=()=>{const location=useLocation(),m=modules[location.pathname.slice(1)]||modules.backtest;return <><PageHeading eyebrow="RESEARCH / NEXT PHASE" title={m.title} subtitle={m.description}><Badge id="module-phase-badge">NOT ENABLED</Badge></PageHeading><EmptyState id="module-empty-state" icon={m.icon} title={m.empty} text={m.text} action={<Button asChild variant="outline" data-testid="module-connections-link"><Link to="/connections">Review connections <ArrowUpRight size={13}/></Link></Button>}/><section className="content-section"><h2 className="section-title">Required before activation</h2><div className="provider-roadmap">{m.requirements.map((r,i)=><div data-testid={`module-requirement-${i}`} key={r}><span>{r}</span><LockKeyhole size={14}/></div>)}</div></section><div className="roadmap-banner" data-testid="module-integrity-note"><ShieldCheck size={17}/>No performance claims or market data are substituted while these requirements are unmet.</div></>};

export const ModelLab=({user})=>{const [data,setData]=useState(null);useEffect(()=>{if(user)api.get('/system').then(r=>setData(r.data)).catch(()=>{});},[user]);return <><PageHeading eyebrow="INTELLIGENCE / MODEL OPERATIONS" title="Model lab" subtitle="Measured intelligence. Bounded cost. No promises of profit."><Badge id="model-provider">GOOGLE GEMINI</Badge></PageHeading><div className="metrics-row"><Metric label="Requests today" value={data?.requests_today??0} note="Research and connection tests" icon={Sparkles} id="llm-requests"/><Metric label="Reported tokens today" value={data?.tokens_today??0} note="Provider-reported usage only" icon={BrainCircuit} id="llm-tokens"/><Metric label="Estimated cost" value={data?.estimated_cost===0?'$0.00':'—'} note="Pricing not configured; not inferred" icon={Activity} id="llm-cost"/><Metric label="Daily research budget" value="10 RUNS" note="1 concurrent run · snapshot caching" icon={ShieldCheck} id="llm-budget"/></div><div className="settings-list"><div className="settings-row" data-testid="model-analyst-routing"><div><h3>Analysts & debate</h3><p>Cost-efficient Gemini tier for high-volume research.</p></div><b>{data?.quick_model||'Gemini Flash Lite'}</b></div><div className="settings-row" data-testid="model-manager-routing"><div><h3>Research, trader & portfolio synthesis</h3><p>Stronger reasoning tier. No direct execution authority.</p></div><b>{data?.deep_model||'Gemini Pro'}</b></div><div className="settings-row" data-testid="model-quant-routing"><div><h3>Quant calculations & risk</h3><p>Indicators, costs and risk limits computed locally.</p></div><b>PYTHON · CPU</b></div></div><EmptyState id="model-evaluation-empty" icon={FlaskConical} title="Performance is earned, not assumed." text="Calibration, Brier score and regime-conditioned performance require settled predictions and out-of-sample evidence."/></>};